### ISSUE TITLE
add ssh error message

### ISSUE THREAD

**Issue by notapoptab** [swcarpentry/git-novice#909] opened 2022-12-20 17:56 UTC
Members of organizations may not be aware if the appropriate ports have been opened by their IT departments for ssh to work. While ssh is a more secure protocol, some places are reticent to open ports for it to work.

It may be worth adding a quick screenshot or flag as to what the error message looks like if ssh will not work in an organization. With that, it should be mentioned that participants will need to use https.

I am happy to do the pull request with the error if this would be helpful to others, just let me know :)

**Comment by kekoziar** [comment] 2023-02-06 23:07
related to #864

**Comment by martinosorb** [comment] 2024-07-18 08:05
Closing as duplicate of #864.

**Closed by martinosorb** 2024-07-18 08:05 UTC
