### ISSUE TITLE
Transition To Workbench in May

### ISSUE THREAD

**Issue by zkamvar** [swcarpentry/git-novice#915] opened 2023-04-25 18:34 UTC
@swcarpentry/git-novice-maintainers

As I hope you are already aware, we are rolling out the new lesson infrastructure, [The Carpentries Workbench](https://carpentries.github.io/workbench/), across all of The Carpentries official lessons in early May 2023. This means that all Data Carpentry, Library Carpentry, and Software Carpentry lesson repositories will be modified to adopt the new infrastructure in the coming days.

You can follow the transition of this lesson repository at https://github.com/carpentries/lesson-transition/issues/72.

The transition has already taken place for several lessons, and so far the process has been running quite smoothly. You should see the transition take place with minimal disruption, but there are a few things that it is important for Maintainers to be aware of. 

Here is what you can expect to happen next:

1. Any open pull requests on the repository will be closed with an automated message.
2. The repository will be set to read-only mode for a brief period while the transition occurs.
3. The new repository structure and lesson site layout will then be applied.
4. To avoid anyone accidentally pushing the old commit history back to the repository, after the transition Maintainers will need to delete and replace any existing forks and local clones they have of the lesson repository, and confirm that they have done so by replying to this issue.

I will reply here before and after the transition has taken place. If you have any questions in the meantime, please reach out to the Curriculum Team by tagging us here, e.g. @swcarpentry/core-team-curriculum.

If you would like to read more about the new lesson infrastructure and the modified repository structure you can expect post-transition, I recommend [the Infrastructure episode of the Maintainer Onboarding curriculum](https://carpentries.github.io/maintainer-onboarding/05-infrastructure.html) and [the Workbench Transition Guide](https://carpentries.github.io/workbench/transition-guide.html), which includes a side-by-side comparison of various elements of the old and new infrastructures.

**Comment by kekoziar** [comment] 2023-04-30 23:07
@swcarpentry/core-team-curriculum  I have some questions that I also sent via email and added to slack.  I'll restate them here
1. what will happen to the development branches?  We have one to develop a supplementary episode on advanced ssh.
2. when I looked at the preview, nothing is under "More" in the Instructor View.  Shouldn't there be something there?
3. I looked for info on the difference between instructor and learner view, but couldn't find anything.
4. not sent via email, but want to echo concern with the FIXMEFIXME headers that were part of the original lesson template and are showing up in the lessons in the new infrastructure. 

Thanks for your work on this!

**Comment by zkamvar** [comment] 2023-05-01 14:15
> what will happen to the development branches? We have one to develop a supplementary episode on advanced ssh.

Nothing will happen to these branches and I can help you transition this episode after the transition is over. That being said, you can use `episode_order` in the setup to create a schedule for the current episodes and then merge in the `ssh-adv` branch. This way, that episode will retain the commit history and be transitioned, but it will remain in draft form.  

> when I looked at the preview, nothing is under "More" in the Instructor View. Shouldn't there be something there?
I looked for info on the difference between instructor and learner view, but couldn't find anything.

see https://carpentries.github.io/workbench/transition-guide.html#navigation and https://carpentries.github.io/workbench/transition-guide.html#folder-structure

> not sent via email, but want to echo concern with the FIXMEFIXME headers that were part of the original lesson template and are showing up in the lessons in the new infrastructure.

This was fixed and should not be a problem anymore (see https://github.com/carpentries/workbench/issues/45#issuecomment-1523857703). I'll push the updated preview in the next hour.

**Comment by kekoziar** [comment] 2023-05-01 16:52
@zkamvar Thank you for the quick reply and additional links. 

> > what will happen to the development branches? We have one to develop a supplementary episode on advanced ssh.
> 
> Nothing will happen to these branches and I can help you transition this episode after the transition is over. That being said, you can use `episode_order` in the setup to create a schedule for the current episodes and then merge in the `ssh-adv` branch. This way, that episode will retain the commit history and be transitioned, but it will remain in draft form.

Cool.  I'll ping you when we're ready to merge the branch - which I'm guessing will be sometime the second half of this year.


> > when I looked at the preview, nothing is under "More" in the Instructor View. Shouldn't there be something there?
> > I looked for info on the difference between instructor and learner view, but couldn't find anything.
> 
> see https://carpentries.github.io/workbench/transition-guide.html#navigation and https://carpentries.github.io/workbench/transition-guide.html#folder-structure

I was hoping for a grid that was a manifest of common items in lessons along with checkmarks or other indications to which view(s) the items are supposed to be in. 

While I understand removing instructor-only notes from a learner view, there is a lot of content that was removed from the instructor view and is only available in learner view.  The linked transition guide states under "Instructor View," _"The “More” dropdown menu contains information for learners from the `instructors/` folder."_ but, in the ["Inspired Examples" lessons on the workbench](https://carpentries.github.io/workbench/#inspired-examples), the "More" dropdown menus are empty in Instructor View. 

It’s odd, and imo erroneous, that things like reference material and glossaries are only available to learners, because instructors use them also, but now they have to toggle back and forth between views in order to access them.  Again, that's why I was looking for an easy to read manifest to see if this is an actual error or working as intended.  Perhaps there is a pedagogical reason the items are removed from Instructor View?

I'm also very confused why "Learner Profiles" are in the Learner View when learner profiles are a pedagogical term used to help instructors create and use assessments.  Using that term can create confusion in learners - it's not something they've usually come across unless they've had pedagogy training. It might be better to rename that something along the lines of "who takes this lesson."  And the content of learner profiles, in general, is more useful to instructors than to learners, but it is missing from the Instructor View. 

 
> > not sent via email, but want to echo concern with the FIXMEFIXME headers that were part of the original lesson template and are showing up in the lessons in the new infrastructure.
> 
> This was fixed and should not be a problem anymore (see [carpentries/workbench#45 (comment)](https://github.com/carpentries/workbench/issues/45#issuecomment-1523857703)). I'll push the updated preview in the next hour.

Awesome. Thanks for the update!

**Comment by kekoziar** [comment] 2023-05-01 17:04
@zkamvar fyi on our PRs.  Except for @tobyhodges #916, all of the ones I'm going to merge or close have been merged or closed.  The PRs which are left open are waiting for contributor responses.  Is the deadline to merge basically one or two days before the transition date?  Our date is Sunday May 7th. I can check in and merge/close this Friday (May 5th).  If the merge deadline is today, I'm okay with them auto-closing when the transition takes place, as they have labels which will allow us to find and recreate if needed. But, I'd prefer they stay open since it will be easier and less confusing for contributors to respond.

**Comment by zkamvar** [comment] 2023-05-01 17:31
> The PRs which are left open are waiting for contributor responses. Is the deadline to merge basically one or two days before the transition date?

Yes. That is correct. 

> Our date is Sunday May 7th.

It's actually May 8th 🙈. I don't tend to work on Sundays, sorry about that. I will update the dates for everyone on this day. 

FWIW, all of the auto-closed PRs will have [the `pre-workbench` label](https://github.com/search?q=org%3ALibraryCarpentry+label%3Apre-workbench&type=pullrequests), so it will be easier to find exactly the ones that were closed due to the transition.

**Comment by kekoziar** [comment] 2023-05-01 17:41
> FWIW, all of the auto-closed PRs will have [the `pre-workbench` label](https://github.com/search?q=org%3ALibraryCarpentry+label%3Apre-workbench&type=pullrequests), so it will be easier to find exactly the ones that were closed due to the transition.

Cool.  Thanks for letting me know.

**Comment by zkamvar** [comment] 2023-05-08 15:04
This lesson will be converted to use [The Carpentries Workbench][workbench]
To prevent accidental reversion of the changes, we are temporarily revoking
write access for all collaborators on this lesson:

 - [ ] @richmccue (push)
 - [ ] @scottgruber (push)
 - [ ] @coatless (push)
 - [ ] @annajiat (push)
 - [ ] @munkm (push)
 - [ ] @nhejazi (push)
 - [ ] @kekoziar (push)
 - [ ] @mxiang1 (push)
 - [ ] @Gina123-P (push)

If you no longer wish to have write access to this repository, you do not
need to do anything further.

1. What you can expect from the transition 📹: https://carpentries.github.io/workbench/beta-phase.html#beta
2. How to update your local clone 💻: https://carpentries.github.io/workbench/beta-phase.html#updating-clone
3. How to update (delete) your fork (if you have one) 📹: https://carpentries.github.io/workbench/faq.html#update-fork-from-styles

If you wish to regain write access, please re-clone the repository on your machine and
then comment here with `I am ready for write access :rocket:` and the
admin maintainer of this repository will restore your permissions.

If you have any questions, please reply here and tag @zkamvar

[workbench]: https://carpentries.github.io/workbench

**Comment by zkamvar** [comment] 2023-05-08 15:06
The deed is done. The infrastructure takes a few minutes to bootstrap and cache the packages for the lesson build. Once the build is done, I will switch github pages to deploy from the `gh-pages` branch and you will have your workbench lesson. 

Thank you all for your enthusiasm and your patience!

**Comment by zkamvar** [comment] 2023-05-08 15:26
The Workbench version is now live: https://swcarpentry.github.io/git-novice/

In addition, here is [map of commits that were changed during the transition](https://github.com/carpentries/lesson-transition/blob/release_swc/git-novice/release/swcarpentry/git-novice-commit-map.hash)

**Comment by kekoziar** [comment] 2023-05-09 17:13
I am ready for write access :rocket:

**Comment by zkamvar** [comment] 2023-05-09 17:30
@kekoziar access granted!

**Comment by kekoziar** [comment] 2023-08-14 18:05
Hi, @zkamvar.  Will you confirm who else are maintainers for this lesson? By my count, and according to the SWC groups, only you and I are listed in the git lesson workbench maintainer group (and thus maintainers for the lesson).  I added a PR to fix a couple of links in the lesson that needed to be updated because of the transition to the new infrastructure, and am looking for a different maintainer to review and approve my PR (which has been our workflow since I've been maintaining the lesson).  Any assistance is appreciated.  Thanks!

**Comment by zkamvar** [comment] 2023-08-14 19:03
Hi @kekoziar, this list will have the maintainers who are currently on the lesson and who have responded to the opt-in survey earlier this year: https://software-carpentry.org/lessons/

@munkm, @nhejazi, and @scottgruber please confirm that you have followed the instructions in https://github.com/swcarpentry/git-novice/issues/915#issuecomment-1538511464 and reply here with `I am ready for write access :rocket:`. 

For each person that responds, I or @ErinBecker will add them to the temporary @swcarpentry/git-novice-maintainers-workbench team so that they can continue maintenance. Once all maintainers have confirmed that they have followed the instructions and reset their local clones, then the @swcarpentry/git-novice-maintainers will have maintain access resotred and the `maintainers-workbench` team will be removed. 

The reason for this stringency is because until local clones and forks are reset, it is possible for someone to accidentally force push outdated changes to the main or gh-pages branches.

In the meantime, I have reviewed the pull request you created.

**Comment by zkamvar** [comment] 2023-09-27 13:15
@munkm, @nhejazi, and @scottgruber please confirm that you have followed the instructions in https://github.com/swcarpentry/git-novice/issues/915#issuecomment-1538511464 and reply here with `I am ready for write access :rocket:`

Effectively, we ask that you delete your local copy of the lesson and re-clone.

**Comment by ErinBecker** [comment] 2023-11-20 16:37
Hi @munkm, @nhejazi, and @scottgruber - You no longer have Maintainer access to this repository. Please see the comment above for details. If you would like to restore your access, please re-clone the repository on your machine and then comment here with I am ready for write access :rocket: and the admin maintainer of this repository will restore your permissions. If you have any questions, please don’t hesitate to get in touch curriculum@carpentries.org

To the remaining Maintainers for this lesson - the Curriculum Team will be prioritizing onboarding of new Maintainers for lessons that have lost Maintainers in our next round of onboarding. Please don’t hesitate to reach out if your lesson needs additional support in the meantime - [curriculum@carpentries.org](mailto:curriculum@carpentries.org).

I will close this issue now but will still be notified of any replies on the thread in future.

**Closed by ErinBecker** 2023-11-20 16:37 UTC
Labels: type:template and tools
