### ISSUE TITLE
Outdated screenshots referencing "planets" repository

### ISSUE THREAD

**Issue by exn297** [swcarpentry/git-novice#1056] opened 2024-12-06 20:34 UTC
### What is the problem?

There are four screenshots in **Episode 7. Remotes in GitHub** that reference the outdated repository "planets."

### Location of problem (optional)

https://swcarpentry.github.io/git-novice/07-github.html

**Comment by martinosorb** [comment] 2024-12-08 11:55
Duplicate of #1033. Thanks.

**Closed by martinosorb** 2024-12-08 11:55 UTC
