### ISSUE TITLE
Don't describe git as 'automated' version control

### ISSUE THREAD

**Issue by js-robinson** [swcarpentry/git-novice#455] opened 2017-12-06 14:40 UTC
This page http://swcarpentry.github.io/git-novice/01-basics/ describes git / svn etc. as Automated version control systems, which suggests automation, i.e. that the user doesn't need to do anything in order to record revisions.

This is not a commonly used term and could confuse users.

**Comment by djinnome** [comment] 2017-12-06 17:29
Perhaps a better  for description of git, svn, cvs, rcs, etc would  be just 'version control system'.  This could then be further categorized where git, mercurial, etc would be 'distributed' version control systems and  SVN, CVS, etc would be 'centralized' version control systems.

**Comment by iglpdc** [comment] 2017-12-07 02:48
I understand "automated" in the lesson as not completely manual, instead of completly automated. People would argue that naming the files with the date there were updated or appending  "_v_1",  "_v_2", etc... is a version control system. Our learners are typically unaware of the existence of version control software, so the step of going from this "manual" version control system to git or svn automates a big part of their versioning.

I would not introduce distributed vs centralized, but maybe a better description clarifiying that is not fully automatic (say like Word autosave or Dropbox versioning) is needed.

What about "automated version control" -> "software/system that automates/helps automatizing (if this is word) part of the versioning process/hassle/burden..."?

**Comment by djinnome** [comment] 2017-12-07 03:02
Perhaps a better way to help our git novices understand the value of a version control system like git is to have them first implement a [manual version control system ](https://swcarpentry.github.io/good-enough-practices-in-scientific-computing/) as suggested in [issue #429](https://github.com/swcarpentry/git-novice/issues/429)

**Comment by iglpdc** [comment] 2018-03-22 03:32
See also #382

**Comment by kekoziar** [comment] 2019-07-04 16:45
Duplicate of #382 and starting to go off-track and duplicate #429

**Closed by kekoziar** 2019-07-04 16:45 UTC
Labels: status:duplicate
