### ISSUE TITLE
We should talk more about good commit messages

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/git-novice#190] opened 2015-11-15 08:30 UTC
- http://chris.beams.io/posts/git-commit/
- https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message

**Comment by wking** [comment] 2015-11-16 06:06
On Sun, Nov 15, 2015 at 12:30:35AM -0800, Greg Wilson wrote:
> http://chris.beams.io/posts/git-commit/

Duplicate of #71 and #78?  I think the current sentence and Pope link
(landed in #78) is sufficient for the main text.  But I'd encourage
instructors to dig into this a bit during live coding, if the class
seemed receptive.  And #71 is still open around if/where to have more
docs on this for instructors/students who want a deeper dive in our
lessons.

**Comment by iglpdc** [comment] 2016-01-31 21:54
I found this guide that AngularJS [1] uses and could also serve as inspiration.

[1] https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines

**Comment by iglpdc** [comment] 2016-06-14 14:31
There's a good discussion on #71 that should be taking into account here.

**Closed** 2017-02-07 19:10 UTC
Labels: enhancement
