### ISSUE TITLE
Git on old Macs

### ISSUE THREAD

**Issue by DamienIrving** [swcarpentry/git-novice#32] opened 2015-01-23 05:44 UTC
[This blog post](http://www.software-carpentry.org/blog/2015/01/instructor-debriefing.html) talks about the problem participants often have using git on older Mac laptops. It offers [this site](https://www.kernel.org/pub/software/scm/git/) as a solution, which is an archive of older versions git. I'm thinking we need a short guidance document to provide some instructions on how to use that repository of old Git versions. For instance, which versions match up with which releases of Mac OS X? What do you do with one of the files once you've download it?

**Comment by jiffyclub** [comment] 2015-01-23 06:00
Those appear to be archives of the Git source code, which isn't going to work for us. Maybe this page of downloads? http://sourceforge.net/projects/git-osx-installer/files/

**Comment by DamienIrving** [comment] 2015-02-01 22:51
It seems the latest version of the [workshop-template](https://github.com/swcarpentry/workshop-template) give the right information:

**For OS X 10.8 and higher**, install Git for Mac by downloading and running [the installer](http://sourceforge.net/projects/git-osx-installer/files/latest/download). After installing Git, there will not be anything in your ```/Applications``` folder, as Git is a command line program. **For older versions of OS X (10.5-10.7)** use the most recent available installer for your OS available [here](http://sourceforge.net/projects/git-osx-installer/files/). Use the Leopard installer for 10.5 and the Snow Leopard installer for 10.6-10.7. 

Couple of things:  

* Can anyone confirm that this works for older Macs?
* Users of newer Macs shouldn't actually need to install anything at all, right? It comes pre-installed. I'm thinking the instructors should be modified to reflect this.

**Comment by jiffyclub** [comment] 2015-02-01 22:59
Both yes and no on that last point. /usr/bin/git exists in 10.9+, but the
first time you use it you have to agree to the Xcode terms and it might
actually download the developer tools then? (I could be wrong on specifics
here, but I dunno how to test...)

**Comment by jiffyclub** [comment] 2015-02-02 18:25
Does anyone know if the git-osx-installers add /usr/local/git/bin to the user's PATH, or must that be done manually?

**Comment by jiffyclub** [comment] 2015-02-02 18:43
I just installed from http://sourceforge.net/projects/git-osx-installer/files/ and it installs to /usr/local/git, but it doesn't seem to modify your PATH, so users may have to do this manually. I also found that OS X didn't want to open the installer because it doesn't come from a trusted developer, you have to do the right-click > Open trick. So those are some things we might need to note. Other people have experience with that?

**Comment by andreabedini** [comment] 2015-02-12 23:37
The common way to install software on OSX is to use [homebrew](http://brew.sh/), I think it supports older versions of OSX too but I need to verify. That would be the perfect solution because with the same tool you can install also python, r, and whatever, there's heaps of packages.

**Comment by jiffyclub** [comment] 2015-02-12 23:41
Most of our students do not know how to use the shell before our workshops, so installing things via homebrew is a bit much to ask of them.

**Comment by ethanwhite** [comment] 2015-02-12 23:57
> Most of our students do not know how to use the shell before our workshops, so installing things via homebrew is a bit much to ask of them.

Agreed.

**Comment by andreabedini** [comment] 2015-02-13 00:29
@jiffyclub @ethanwhite I understand, but I thought the problem was that the students had to fix their PATH, which is even worse.

**Comment by jiffyclub** [comment] 2015-02-13 00:37
At this point I really don't have a clear enough picture about what exactly people with versions of OS X older than 10.8 have to do. Unless someone here access to a computer running 10.6-7 and can test things, we may have to wait until someone brings in a complete report from a workshop.

**Comment by andreabedini** [comment] 2015-02-13 00:50
@jiffyclub I might have some old macs in my lab, I'll do some tests and report back (be aware that my report could include "please upgrade" :-))

**Comment by jiffyclub** [comment] 2015-02-13 00:55
That'd be great, especially if they are really fresh. E.g., don't have Xcode or any command line tools or anything else installed.

I really wish everyone would upgrade to at least a semi-recent OS, but sadly it's not an option at a workshop or with some managed equipment.

**Comment by jduckles** [comment] 2015-02-13 01:13
On older mac homebrew requires a ~2GB download of XCode to just get started with homebrew, not gonna happen with shaky wifi. As @DamienIrving mentions this was fixed in the swcarpentry/workshop-template#134 and confirmed to work at a workshop in January.

**Comment by jduckles** [comment] 2015-02-13 01:14
@jiffyclub, the user I installed it for was able to use it with no PATH modification, I've had to do this a couple of times in the past and I don't recall modifying PATH's.

**Comment by jiffyclub** [comment] 2015-02-13 03:50
@jduckles, thanks for the report! We can probably close this, then.

**Comment by jduckles** [comment] 2015-02-13 03:58
@jiffyclub Agreed, stick with the sourceforge links, not the kernel.org stuff tarballs.

**Comment by iglpdc** [comment] 2015-02-13 05:48
Good. I've updated the [wiki at the workshop-template repo](https://github.com/swcarpentry/workshop-template/wiki/Configuration-Problems-and-Solutions) to reflect this.

**Closed by iglpdc** 2015-02-13 05:48 UTC
