### ISSUE TITLE
Issues at 01-backup.md

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/git-novice#29] opened 2015-01-21 19:02 UTC
From https://raw.githubusercontent.com/swcarpentry/lesson-template/gh-pages/tools/check.py:

- [x] Header section is missing expected row 'minutes'
- [x] Heading at line 28 should be level 2
- [x] Heading at line 75 should be level 2
- [x] Heading at line 128 should be level 2
- [x] Heading at line 273 should be level 2
- [x] Heading at line 510 should be level 2
- [x] Heading at line 595 should be level 2
- [x] Heading at line 692 should be level 2
- [ ] Document contains heading not specified in the template: Setting Up
- [ ] Document contains heading not specified in the template: Creating a Repository
- [ ] Document contains heading not specified in the template: Tracking Changes to Files
- [ ] Document contains heading not specified in the template: Changing a File
- [ ] Document contains heading not specified in the template: Exploring History
- [ ] Document contains heading not specified in the template: Recovering Old Versions
- [ ] Document contains heading not specified in the template: Ignoring Things
- [ ] The topic page should not have sub-headings outside of special blocks. If a topic needs sub-headings, it should be broken into multiple topics.

**Comment by iglpdc** [comment] 2015-02-11 14:18
Partly fixed in #37. I marked as completed the corresponding tasks above.

**Comment by iglpdc** [comment] 2015-02-22 17:06
I want to fix the issues with this file to conform with the lesson template. The problem is that to do that either this topic is broken into several parts (I see three: setup and git init, add-diff-commit cycle, and exploring history), or we simply remove the headers separating the different subtopics (I think this will make a very long, unstructured file). 

Thoughts?

**Comment by gvwilson** [comment] 2015-02-22 17:28
Hi Ivan,
Please break it into pieces - it really wants to be smaller chunks. 
That'll mean renumbering subsequent files...

**Comment by iglpdc** [comment] 2015-02-22 17:30
Good, I will.

**Closed** 2015-03-17 19:34 UTC
Labels: bug
